// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rweeosslihcnimkogcyj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ3ZWVvc3NsaWhjbmlta29nY3lqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTExMDExODEsImV4cCI6MjA2NjY3NzE4MX0.pC5CYfBwI-ZKaxpcTzCtpeRD364bZgpKx52KsYVjjms";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);